datadir: /opt/nuts/data
strictmode: false
http:
  default:
    address: :1323
    cors:
      origin: "*"
verbosity: debug
network:
  enabletls: false
  disablenodeauthentication: true
  v2:
    gossipinterval: 500
