datadir: /opt/nuts/data
http:
  default:
    address: :1323
    cors:
      origin: "*"
auth:
  irma:
    autoupdateschemas: false
#verbosity: debug
network:
  enabletls: false
  bootstrapnodes:
    - "node1:5555"
#    - "node2:5555"
    - "node3:5555"
    - "node4:5555"
    - "node5:5555"
