verbosity: debug
address: :1323
auth:
  actingPartyCn: Demo EHR
  publicUrl: https://example.org
  irmaConfigPath: /opt/nuts/irma
  skipAutoUpdateIrmaSchemas: true
  enableCORS: true
crypto:
  fspath: /opt/nuts/keys
registry:
  datadir: /opt/nuts/registry
events:
  zmqAddress: tcp://bundy-bridge:5563
  connectionstring: file:eventstore.db
cbridge:
  address: http://bundy-bridge:8080
cstore:
  connectionstring: /opt/nuts/sqlite/sqlite.db
